/******************************************************************************
Copyright (c) 2020  Sebastian Krawczyk

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
******************************************************************************/

#ifndef PORT_H_
#define PORT_H_

/******************************************************************************
WAVESHARE 320X240
******************************************************************************/

//#define LCD_HX8347D_CS				PA3
//#define LCD_HX8347D_CS_BIT			PA3
//#define LCD_HX8347D_CS_PORT_DDR		DDRA
//#define LCD_HX8347D_CS_PORT			PORTA
//#define LCD_HX8347D_CS_PIN			PINA
//#define LCD_HX8347D_CS_OUT()		( LCD_HX8347D_CS_PORT_DDR |= ( 1 << LCD_HX8347D_CS_BIT ) )
//#define LCD_HX8347D_CS_ENABLE()		( LCD_HX8347D_CS_PORT &= ~( 1 << LCD_HX8347D_CS_BIT ) )
//#define LCD_HX8347D_CS_DISABLE()	( LCD_HX8347D_CS_PORT |=  ( 1 << LCD_HX8347D_CS_BIT ) )

//#define LCD_HX8347D_DC				PA2
//#define LCD_HX8347D_DC_BIT			PA2
//#define LCD_HX8347D_DC_PORT_DDR		DDRA
//#define LCD_HX8347D_DC_PORT			PORTA
//#define LCD_HX8347D_DC_PIN			PINA
//#define LCD_HX8347D_DC_OUT()		( LCD_HX8347D_DC_PORT_DDR |= ( 1 << LCD_HX8347D_DC_BIT ) )
//#define LCD_HX8347D_DC_COMMAND()	( LCD_HX8347D_DC_PORT &= ~( 1 << LCD_HX8347D_DC_BIT ) )
//#define LCD_HX8347D_DC_DATA()		( LCD_HX8347D_DC_PORT |=  ( 1 << LCD_HX8347D_DC_BIT ) )

//#define LCD_WAVESHARE_320X240_BL			PL7
//#define LCD_WAVESHARE_320X240_BL_BIT		PL7
//#define LCD_WAVESHARE_320X240_BL_PORT_DDR	DDRL
//#define LCD_WAVESHARE_320X240_BL_PORT		PORTL
//#define LCD_WAVESHARE_320X240_BL_PIN		PINL
//#define LCD_WAVESHARE_320X240_BL_OUT()		( LCD_WAVESHARE_320X240_BL_PORT_DDR |=  ( 1 << LCD_WAVESHARE_320X240_BL_BIT ) )
//#define LCD_WAVESHARE_320X240_BL_OFF()		( LCD_WAVESHARE_320X240_BL_PORT &= ~( 1 << LCD_WAVESHARE_320X240_BL_BIT ) )
//#define LCD_WAVESHARE_320X240_BL_ON()		( LCD_WAVESHARE_320X240_BL_PORT |=  ( 1 << LCD_WAVESHARE_320X240_BL_BIT ) )

#endif /* PORT_H_ */